/*******************************************************************************
 *
 * Copyright (C) 2004 Depik Technologies Pvt. Ltd All rights reserved
 *
 * The information and source code contained herein is the exclusive property
 * of Depik Technologies Pvt. Ltd and may not be disclosed, examined or 
 * reproduced in whole in part without the explicit written autherization 
 * from Depik Technologies.
 ******************************************************************************/
/*
 * Do not edit this file, this file will be used at the time of
 * compilation.  On changing this file may cause UNPREDICTABLE
 * results.
 */
#include "symtable.h"

symTab_t symbols[1000]      = 
{
};

int noOfSymbols = 557;
